// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Data;

#nullable disable

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20230612154949_Add Product table and seed for it")]
    partial class AddProducttableandseedforit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("ProductAPI.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gaming Keyboard with lights",
                            Name = "Keyboard",
                            Price = 150,
                            ProductType = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gaming Mouse",
                            Name = "Mouse",
                            Price = 40,
                            ProductType = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "HD monitor",
                            Name = "Monitor",
                            Price = 400,
                            ProductType = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Business Cabinet with lights",
                            Name = "Cabinet",
                            Price = 60,
                            ProductType = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
